sudo: required

dist: xenial

#osx_image: xcode7.3

os:
  - linux
#  - osx

language: cpp

compiler: gcc

node_js:
  - node

branches:
  only: master

git:
  depth: false

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages: ['g++-8', 'clang-tidy-6.0', 'cowsay']

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 50
      sudo update-alternatives --install /usr/bin/x86_64-linux-gnu-g++ x86_64-linux-gnu-g++ /usr/bin/x86_64-linux-gnu-g++-8 50
      gem install coveralls-lcov
      npm install -g codacy-coverage npm-check-updates
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew install --with-default-names gnu-sed
    fi

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      yes 1 | KUNITS=1 make install dist K
      (cd /var/lib/K && ncu)                  | sed '/^\s*$/d' | /usr/games/cowsay -nW80 -fduck
      make test-c                                              | /usr/games/cowsay -nW160 -felephant || :
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      yes 4 | make install
    else
      yes 5 | make install
    fi

script: make test             | sed '/^\s*$/d' | sed '/====/d' | /usr/games/cowsay -nW160 -fbud-frogs && test ${PIPESTATUS[0]} -eq 0

after_success:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      lcov -o cov.info -c -d . --gcov-tool /usr/bin/gcov-8     > /dev/null 2>&1
      lcov -o cov.info -r cov.info '/usr/*' '*local/include/*' > /dev/null 2>&1
      lcov -l cov.info                                         | /usr/games/cowsay -nW80 -fdefault
      coveralls-lcov cov.info                                  > /dev/null 2>&1
      cat cov.info | codacy-coverage --language cpp            > /dev/null 2>&1
    fi

notifications:
  email:
    on_success: never
